'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UsefulControl.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 一、支持参数
        '''  使用 /nosaveprofile 以安全模式启动（不保存配置），仅支持显示在左侧
        '''  使用 /leftbar 以工具栏形式启动显示在屏幕左侧 
        '''  使用 /rightbar 以工具栏形式启动显示在屏幕右侧 
        '''  使用 /topbar 以工具栏形式启动显示在屏幕顶部
        '''  使用 /bottombar 以工具栏形式启动显示在屏幕底部
        '''  使用 /lefttopbar 以工具栏形式启动显示在屏幕左上角 
        '''  使用 /righttopbar 以工具栏形式启动显示在屏幕右上角 
        '''  使用 /leftbottombar 以工具栏形式启动显示在屏幕左下角 
        '''  使用 /rightbottombar 以工具栏形式启动显示在屏幕右下角 
        '''
        '''  使用 /closescr 参数关屏幕并启动黑屏。
        '''  使用 /blankscr 参数启动黑屏。
        '''  使用 /fakeshutdown 参数启动伪关机界面（希沃）。
        '''  使用 /fakeshutdownlenovo 参数启动伪关机界面（联想）。
        '''  使用 /locktime 参数启动时钟锁屏。
        '''  使用 /locktime2 参数启动时钟锁 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property DocText() As String
            Get
                Return ResourceManager.GetString("DocText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似                     GNU GENERAL PUBLIC LICENSE
        '''                       Version 3, 29 June 2007
        '''
        ''' Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        ''' Everyone is permitted to copy and distribute verbatim copies
        ''' of this license document, but changing it is not allowed.
        '''
        '''                            Preamble
        '''
        '''  The GNU General Public License is a free, copyleft license for
        '''software and other kinds of works.
        '''
        '''  The licenses for most software and other practical works are designed
        '''to [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GPL3() As String
            Get
                Return ResourceManager.GetString("GPL3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 一、加载说明
        '''      本程序在启动时会自动加载程序所在根目录名为 ShowImage 的图片，加载格式根据以下优先级排列
        ''' （.png &gt; .jpg &gt; .bmp &gt; .tiff  &gt; .ico &gt; .gif），即优先加载较前的文件格式，如果在设置勾选了加载
        '''  上一次打开的图片，则当ShowImage没有被加载时，自动加载上一次的图片。
        '''二、功能说明
        '''  1.双击图片展示区域可隐藏标题栏。
        '''  2.部分功能可能因为策略设置而不可用。命令行的内容要优先于策略设置，针对所有用户设置的策略优先
        '''    级高于为单一用户设置的策略。
        '''  3.使用 /nosaveprofile 参数启动不保存用户设置。 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property IBoardDocText() As String
            Get
                Return ResourceManager.GetString("IBoardDocText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property lenovoshut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lenovoshut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property seewodialog_btn_left_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seewodialog_btn_left_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property seewodialog_btn_left_pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seewodialog_btn_left_pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property seewodialog_btn_right_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seewodialog_btn_right_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property seewodialog_btn_right_pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seewodialog_btn_right_pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
